#!/bin/bash
echo "All variables passed:$@"
echo "number of varaibles:$#"
echo "to know vscode script name:$0"
echo "present working directory:$PWD"
echo "home directory of current user:$HOME"
echo "which user is running in script:$USER"
echo "processs id of current user:$$"
echo "sleep 60"
echo "process id of last command in background:$#"
